"""
노드 5 — Newsletter Writer (뉴스레터 작성)

큐레이션된 기사들로 프리미엄 뉴스레터 초안을 생성한다.
- 마크다운 형식
- Claude에 바로 붙여넣기 가능한 형태
- 파일로 자동 저장
"""

from __future__ import annotations

import os
from datetime import datetime

from langchain_core.messages import SystemMessage, HumanMessage

from state import NewsHubState
from llm_factory import get_llm


def newsletter_writer_node(state: NewsHubState) -> dict:
    """큐레이션된 기사로 뉴스레터 초안을 작성한다."""

    curated_articles = state.get("curated_articles", [])
    trend_summary = state.get("trend_summary", "")
    topics = state.get("topics", ["AI"])

    if not curated_articles:
        return {
            "newsletter_draft": "# 뉴스레터를 생성할 기사가 없습니다.\n\n토픽이나 소스를 확인해주세요.",
            "newsletter_format": "markdown",
        }

    # 기사 정보를 텍스트로 변환
    articles_text = ""
    for i, article in enumerate(curated_articles, 1):
        score = article.get("score", 0)
        articles_text += f"""
[기사 {i}] (관련도: {score:.0%})
제목: {article.get('title', '제목 없음')}
소스: {article.get('source', '알 수 없음')}
요약: {article.get('summary', '요약 없음')[:300]}
URL: {article.get('url', '')}
태그: {', '.join(article.get('tags', []))}
---
"""

    llm = get_llm(temperature=0.7)

    today = datetime.now().strftime("%Y년 %m월 %d일")
    topic_str = ", ".join(topics)

    system_prompt = f"""당신은 프리미엄 뉴스레터 작성 전문가입니다.
아래 큐레이션된 기사들과 트렌드 요약을 바탕으로 멋진 뉴스레터를 작성하세요.

날짜: {today}
관심 토픽: {topic_str}

트렌드 요약:
{trend_summary}

뉴스레터 작성 규칙:
1. 마크다운 형식으로 작성
2. 매력적인 제목 + 부제목
3. 🌟 핵심 트렌드 요약 (3~5줄)
4. 📰 주요 기사 (각 기사에 대해):
   - 기사 제목 + 링크
   - 핵심 내용 2~3줄 요약
   - 💡 시사점/인사이트 1줄
5. 🔮 전망/시사점 (2~3줄)
6. 작성자/서명
7. 이모지를 적절히 활용하여 가독성 향상
8. 한국어로 작성 (기술 용어는 영문 병기)
"""

    try:
        response = llm.invoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=articles_text),
        ])

        newsletter = response.content.strip()

    except Exception as e:
        # LLM 실패 시 기본 템플릿 생성
        newsletter = _fallback_newsletter(curated_articles, topics, trend_summary, today)

    # 파일로 저장
    output_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output")
    os.makedirs(output_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"newsletter_{timestamp}.md"
    filepath = os.path.join(output_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(newsletter)

    return {
        "newsletter_draft": newsletter,
        "newsletter_format": "markdown",
    }


def _fallback_newsletter(articles, topics, trend_summary, today):
    """LLM 실패 시 기본 템플릿으로 뉴스레터 생성"""
    topic_str = ", ".join(topics)

    lines = [
        f"# 📡 NewsHub Daily — {topic_str}",
        f"**{today}** | AI가 큐레이션한 오늘의 뉴스",
        "",
        "---",
        "",
        "## 🌟 트렌드 요약",
        trend_summary or "오늘의 트렌드 정보가 없습니다.",
        "",
        "---",
        "",
        "## 📰 주요 기사",
        "",
    ]

    for i, article in enumerate(articles, 1):
        title = article.get("title", "제목 없음")
        url = article.get("url", "#")
        source = article.get("source", "알 수 없음")
        summary = article.get("summary", "요약 없음")[:200]
        score = article.get("score", 0)

        lines.extend([
            f"### {i}. [{title}]({url})",
            f"📌 **출처**: {source} | **관련도**: {score:.0%}",
            f"> {summary}",
            "",
        ])

    lines.extend([
        "---",
        "",
        "## 🔮 전망",
        "이 뉴스레터는 NewsHub Agent가 자동으로 큐레이션한 기사입니다.",
        "",
        "---",
        f"*Generated by NewsHub Agent on {today}*",
    ])

    return "\n".join(lines)
